"""Hydrodynamic lateral side force generation, leeway, and induced drag."""

from dataclasses import dataclass
import numpy as np
from vpp.core.boat import Boat
from vpp.core.environment import Environment


@dataclass
class InducedHydrodynamics:
    """Induced resistance and lateral hydrodynamic forces."""
    r_i: float           # Induced drag [N]
    f_y_hydro: float     # Hydrodynamic lateral force generated [N]
    leeway_rad: float    # Leeway angle [radians]
    cl_keel: float       # Appendage lift coefficient
    dcl_dbeta: float     # Lift curve slope per radian

    @property
    def leeway_deg(self) -> float:
        """Leeway angle in degrees."""
        return np.rad2deg(self.leeway_rad)


def compute_lift_curve_slope(effective_aspect_ratio: float) -> float:
    """Compute lift curve slope dCl/dbeta [1/rad] for a low-aspect-ratio hydrofoil."""
    ar = max(effective_aspect_ratio, 0.5)
    # Helmbold equation for low aspect ratio lifting surfaces
    # dCL/dalpha = 2 * pi * AR / (sqrt(AR^2 + 4) + 2)
    return (2.0 * np.pi * ar) / (np.sqrt((ar ** 2) + 4.0) + 2.0)


def compute_hydro_side_force(
    boat: Boat,
    v_boat_ms: float,
    leeway_rad: float,
    env: Environment = Environment(),
) -> float:
    """Compute hydrodynamic lateral force generated by keel and rudder at a given leeway angle.
    
    Args:
        boat: Boat instance.
        v_boat_ms: Boat forward speed [m/s].
        leeway_rad: Leeway angle [radians].
        env: Environment instance.
        
    Returns:
        Hydrodynamic lateral force [N].
    """
    v_safe = max(v_boat_ms, 0.05)
    q_water = 0.5 * env.rho_water * (v_safe ** 2)
    lat_area = boat.appendages.total_lateral_area
    ar_eff = boat.appendages.effective_aspect_ratio
    dcl = compute_lift_curve_slope(ar_eff)

    # Nonlinear lift behavior (linear at small angles, stalling at >12 deg)
    beta_deg = np.abs(np.rad2deg(leeway_rad))
    if beta_deg < 12.0:
        cl = dcl * np.sin(leeway_rad)
    else:
        # Post-stall decay
        cl = dcl * np.sin(np.deg2rad(12.0)) * np.cos(np.deg2rad(beta_deg - 12.0))
        if leeway_rad < 0:
            cl = -cl

    return q_water * lat_area * cl


def compute_induced_resistance(
    boat: Boat,
    v_boat_ms: float,
    side_force_n: float,
    env: Environment = Environment(),
) -> InducedHydrodynamics:
    """Compute induced drag and equilibrium leeway angle for a required lateral side force.
    
    Args:
        boat: Boat instance.
        v_boat_ms: Boat forward speed [m/s].
        side_force_n: Required lateral force [N] (from aerodynamics).
        env: Environment instance.
        
    Returns:
        InducedHydrodynamics dataclass.
    """
    v_safe = max(v_boat_ms, 0.05)
    q_water = 0.5 * env.rho_water * (v_safe ** 2)
    lat_area = boat.appendages.total_lateral_area
    ar_eff = boat.appendages.effective_aspect_ratio
    dcl = compute_lift_curve_slope(ar_eff)
    t_eff = boat.appendages.effective_draft or boat.hull.draft_total

    # Lift coefficient required from appendages
    cl_req = side_force_n / max(q_water * lat_area, 1e-4)

    # Solve for leeway angle
    sin_leeway = np.clip(cl_req / dcl, -0.25, 0.25)
    leeway_rad = np.arcsin(sin_leeway)

    # Induced drag from finite span lifting foil:
    # Ri = Fy^2 / (pi * rho * V^2 * T_eff^2 * e)
    # Span efficiency factor e ~ 0.88
    span_eff = 0.88
    denom = np.pi * env.rho_water * (v_safe ** 2) * (t_eff ** 2) * span_eff
    r_i = (side_force_n ** 2) / max(denom, 1e-4)

    return InducedHydrodynamics(
        r_i=r_i,
        f_y_hydro=side_force_n,
        leeway_rad=leeway_rad,
        cl_keel=cl_req,
        dcl_dbeta=dcl,
    )
