FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm@latest

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml* ./
RUN pnpm install

COPY . ./

EXPOSE 3333

CMD ["pnpm", "dev", "--host", "0.0.0.0"]
